Open-EO/openeo-api

swagger.json
Removed specific download endpoints and replaced it with a variable format based endpoint. Changed all date/time related data to ISO8601.
=> Download endpoint, ISO8601 timestamps

swagger.json
See issue #12.
**Merge #14 first!**
=> CORS and authorization

docs/docs/jobs.md, docs/docs/poc.md, swagger.json
Integrated #32 (output format options), #34 (Discovery endpoint to get supported file formats), #13 (Placeholder for /capabilities) and other improvements.
=> Integrated #32, #34, #13 and other improvements.

CHANGELOG.md, docs/guidelines-clients.md, openapi.json
=> Unify casing (and fix a few typos) [correct branch version of previous PR]

.gitignore, README.md, docs/gettingstarted-backends.md, docs/glossary.md
various streamlining tweaks
feel free to cherry-pick or ignore
=> Various README.md and glossary.md tweaks

docs/processes.md, docs/processgraphs.md
feel free to cherry-pick or ignore
=> Docs: various copy tweaks in processgraphs.md and processes.md

docs/glossary.md
=> Be bit more clear about spatiotemporal data cubes in glossary

openapi.json
=> Fix center_wavelength values in eo:bands example

docs/guidelines-clients.md
=> Fix `/.well-known/openeo` url in guidelines-clients.md

errors.json
errors.json: add placeholders in message of CollectionNotFound and ServiceNotFound
=> errors.json: add placeholders in message of CollectionNotFound and ServiceNotFound

CHANGELOG.md, openapi.yaml
Callbacks renamed to "parametrized process graphs". #216
=> #216: Callbacks renamed to "parametrized process graphs"

CHANGELOG.md, openapi.yaml
Simplifies the JSON schemas, partially as proposed in #232. See Changelogs for details.
=> Simplify JSON schemas #232

CHANGELOG.md, openapi.yaml
Solves the pagination part in issue #103
=> Pagination

CHANGELOG.md, openapi.yaml
Fixes #239 by making the process parameters universal and use them also for callbacks.
That's how the processes look like afterwards: https://github.com/Open-EO/openeo-processes/pull/130
=> Better define callback parameters

openapi.yaml, subtype-schemas.json
See issue #245. 
Related PR in processes: https://github.com/Open-EO/openeo-processes/pull/133
=> Labeled arrays (for callbacks)

CHANGELOG.md, openapi.yaml
=> Clarified definition of Location header in `HTTP 201` responses

openapi.yaml
some documentation tweaking suggestions
feel free to cherry pick
=> Documentation tweaks related to user defined processes and process graph parameters

openapi.yaml
Several clarifications: #281, #131, #211, #185
=> Several clarifications

CHANGELOG.md, openapi.yaml
=> User-defined process parameters are recursively defined

.gitignore
=> Re-add some IDE config folders to .gitignore

CHANGELOG.md, openapi.yaml
=> Clarifications for #314, #315

openapi.yaml
Looks a bit long in the OpenAPI file, but is pretty sure once rendered.
=> Fine-tune secondary service examples

CHANGELOG.md, openapi.yaml
see #318
I just required configuration, process_parameters just applies to a subset of services, I think. If we's require process_parameters, it would also be good to require parameters in file_formats, I guess.
=> Require Service Type Config

CHANGELOG.md, openapi.yaml
This adds a possibility to specify the return values processes receive from child processes ("callbacks").
=> Child process return values #350

openapi.yaml
=> Issue #355: add couple of predefined schema subtype examples

CHANGELOG.md, openapi.yaml
A generic proposal for issue #370 to specify two ways to communicate resource usage and time metrics.
Inspired by the VITO implementation and other services found online.
=> Resource usage and time metrics #370

CHANGELOG.md, errors.json
* Clarified `ProcessGraphMissing`
* Added `ProcessInvalid` and `ProcessGraphInvalid`
Fixes #401
=> Clarified error.json, added new error codes

CHANGELOG.md, openapi.yaml
=> Provide link with rel type canonical for batch job results #397

CHANGELOG.md, openapi.yaml
Implements #329 as a parameter to set on the data processing request.
=> Logs: Add data processing parameter for minimum severity #329

openapi.yaml
apparently some more gdal.org links need updating
also see #439
=> Update broken links to some GDAL drivers

CHANGELOG.md, openapi.yaml
=> Clarify the message field in logs

CHANGELOG.md, openapi.yaml
=> Clarify how the well-known document works #460
