Open-EO/openeo-api

docs/docs/arch.md
docs/docs/glossary.md
docs/docs/index.md
docs/docs/poc.md
docs/docs/processgraphs.md
docs/docs/udfs.md

Mentioning UDFs in the glossary is the only real change.
> If terms as common as "API" are included in the glossary, the not so common abbreviation "UDF" should be explained there too. In general the concept of UDFs is worthy of a brief description there IMO - I tried to come up with something, please replace or amend as you see fit.
All other changes are just fixed typos etc.

Add UDFs to glossary

---

docs/jobs.md
openapi.json
processes.json
subscriptions.json

- replaced the last forgotten left/right/top/bottom with west/east/north/south
- fixed some typos
- the description for `south` was wrong a couple of times (probably copy&paste error)
- clarified some sentences
- corrected that spatial_extent must ALWAYS be specified in change notifications (so it's now consistent with the example)

Various improvements

---

.travis.yml
openapi.json
tests/requirements.txt
tests/test_examples.py

inspired by #193:
- I created pytest based test suite ("suite" is big word for a single but parametrized test function) that checks all the examples in openapi.json against their corresponding schema
- found a couple of issues and fixed them
- added pytest run to travis

Pytest based tests to check examples in openapi.json against corresponding schema

---

CHANGELOG.md
openapi.json
tests/test_examples.py

Implements #131 - a job result is now a valid STAC Item that could be shipped with the data.
Only issue I see so far is that you need to specify a geometry and bbox. Is that too burdensome? 
Edit: According to a short survey in the recent dev telco, it is usually not a problem.

STAC for job results (#131)

---

CHANGELOG.md
docs/collections.md
openapi.json
tests/test_examples.py

* First draft to update `GET /collections` and `GET /collections/{collectionId}` to STAC version 0.8.1 (#185).
* Removes optional STAC extensions from the API specification (#176).
* Improves cube:dimensions (#208)
STAC 0.8.1 has not been released yet, I'm waiting for the release to merge this PR, but things should still be compatible with STAC already.

Updating to STAC 0.8.1

---

CHANGELOG.md
openapi.yaml

Changes:
1. Remove support for PROJJSON as CRS. Now that we use CRS as dimension, it would complicate the label handling due to PROJJSON not being a number or string.
2. Don't explicitly specify the subtypes if a general type has been specified. For example, temporal strings are always allowed if strings are allowed thus it's not required to mention them explicitly in schemas. Clients should allow all subtypes for the general types to be passed.
Related PR in processes: https://github.com/Open-EO/openeo-processes/pull/132
Related commit in openeo.org: https://github.com/Open-EO/openeo.org/commit/bf9e8271c5df11a5ea46d5e3c6300df7dd9ad8e2

Cleaning up after recent changes

---

CHANGELOG.md
assets/pg-evi-example.json
assets/pg-schema.json
errors.json
openapi.yaml
package.json

Implementation for issue #161.
This is the master PR for https://github.com/Open-EO/openeo-processes/pull/135.
ToDos:

User-defined processes

---

CHANGELOG.md
openapi.yaml

This parameter got lost during the pagination work for RC1. Re-added it again so that the log endpoints can be queried better while processing. This was meant to be part of RC1. Also improved the description for the log endpoints.

Reintroduced the missing `offset` parameter for log endpoints

---

CHANGELOG.md
openapi.yaml

For batch jobs (`/jobs`), services (`/services`) and sync. processing (`/result`) the property `process_graph` got replaced by `process`. It contains a process graph and optionally all process metadata. For context see #260.

Pass process metadata with data processing requests

---

CHANGELOG.md
openapi.yaml

Replaced `POST /process_graphs` and `PATCH /process_graphs/{process_graph_id}` with `PUT /process_graphs/{process_graph_id}`. See #260 for context.

PUT /process_graphs/{id}

---

CHANGELOG.md
errors.json

Updated errors.json

---

CHANGELOG.md
openapi.yaml

see #285
I think none of the clients (except some of my JS tooling) relies on this / implements this anyway, right? @flahn @bgoesswe @jdries 
For back-ends this is not really a breaking change.
Corresponding process changes are in https://github.com/Open-EO/openeo-processes/pull/151

Link to process examples instead of inlining them. #285

---

CHANGELOG.md
openapi.yaml

This PR adds collection-level assets as optional property to data discovery, allowing to specify thumbnails or process graphs for visualizations as discussed in issue #211. Fully backward-compatible to RC2 as it is an optional addition, which was already possible before through STAC extensions. I just make it explicit here.

Collection-level assets

---

CHANGELOG.md
openapi.yaml

https://openeo.org/documentation/1.0/developers/api/reference.html#operation/authenticate-oidc
under `/credientials/oidc`, the `scopes` fields:
scopes (required)   A list of OpenID Scopes that the client MUST use.
If empty, the default scopes of OpenID Connect MUST be used.
This is bit confusing: it is required on one hand, but can be empty (in which case default scopes must be used)
I'm also not sure what _default_ scopes mean in this context, but as far as I know, only `openid` is a required scope to enable OpenID Connect. I would just simplify the doc to state that.

Finetune OpenID Connect scope documentation

---

openapi.yaml

The size of the diff is larger than what actually changed:
- be more consistent in the order of ResultReference/UserDefinedProcess/ParameterReference . These argument types show up in four places in the docs, and using the same order everywhere makes things more clear
- be more consistent with the `apply/absolute` example. It was now a mix of `array_apply` and `apply`. I also pulled it up into the UserDefinedProcess docs for even more reuse.
- some minor finetuning, title casing and typo fixing

Finetune documentation about user defined processes and process parameters

---

CHANGELOG.md
openapi.yaml

This adds a required field `type` to each UDF runtime in `/udf_runtimes`. This is a breaking change, which means each back-end needs to add the field to be valid against the spec.
Ususally, I'd not like breaking changes in this stage, but recently I worked with @aljacob to improve the results you get from openapi-generator. This change is required to get a well-defined class inheritance for the generated classes, without this change the generated classes are pretty useless. Thus we thought it's an easy fix for back-ends to make the OpenAPI document more future-proof and allow new implementers to auto-generate better code. We hope this eases adoption. 
Due to the breaking change I'm asking for approvals / concerns / vetos from back-ends here. This shouldn't be an issue for clients.

Add type to UDF Runtime for better code generation

---

openapi.yaml

- some minor structure/wording tweaks
- dropped the `The only exception ..` part because that seems redundant or even confusing (it reads a bit like the `links` listing should not change across pages, while the browsing links actually SHOULD change on every page)

Finetune pagination_limit description

---

CHANGELOG.md
assets/pg-schema.json
openapi.yaml

see #305 for reasons and discussions.
Please review carefully and approve, if this change is fine for you. Otherwise comment here.

#305: Add namespace to process graph nodes

---

openapi.yaml

A bit of fine-tuning of the secondary services documentation. Feel free to iterate on this
Also: I noticed various service type listings:
- "WMS or WCS" under `GET /service_types`  and "WMS" and "WFS" in the example
- "WMTS, TMS or WCS" under `POST /services` and "wms" (lower case) in the example
it might be cleaner to make this a bit more consistent, but I didn't touch that yet in this PR

Fine-tune secondary service documentation

---

.spectral.yml
CHANGELOG.md
openapi.yaml

The Parameters for File Formats and Service Types had a JSON Schema based definition, but it was a (too) limited subset. It's now replaced with JSON Schema itself. It's used in other places anyway so code can better be re-used. For back-ends this is not a breaking change, it's fully compatible. Clients may face additional/different schemas (especially an array for type), but it's not a bigger issue, I think.
Additionally, I added descriptions for the JSON Schema properties with links to the actual JSON Schema spec.
This also fixes an invalid enum-example in the /service_types response.

Parameters for File Formats / Service Types

---

CHANGELOG.md
openapi.yaml

I just realized again why we haven't had namespaces ( https://github.com/Open-EO/openeo-api/pull/309 ) in the API: User could simply replace missing pre-defined processes (e.g. normalized_difference) with our "alternative" processing instructions in openeo-processes. Just store it as user-defined process and it still runs. That's now broken with namespaces.
Thus, I partly revert the changes introduced in #309: The default behavior for a process graph is again preferring user-defined over pre-defined processes.
The namespaces are now a backward compatible addition to explicitly choosing the pre- or user-defined process.

Revert namespace default

---

CHANGELOG.md
openapi.yaml

- This clarifies that no default values are applied when properties in PATCH requests are not present.
- It also clarifies that the default value is `null` if the `plan` property is missing from requests.
- Generally, descriptions were improved to better reflect different contexts / HTTP methods.
This PR looks a bit more massive than it actually is...

Clarify default values for PATCH and POST requests

---

CHANGELOG.md
openapi.yaml

Changes with regards to how CORS headers are recommended to be sent. This came up in recent discussions in issue #41 and we realized the current recommendation could lead to security issues (although I don't think it could really be exploited with the current implementations). We figured out the current recommendation was based on a not very well written documentation regarding javascript HTTP request option withCredentials in axios / fetch / XHR. We don't need to provide the `Access-Control-Allow-Credentials` header and can set `Access-Control-Allow-Origin` to `*`. This blocks the potential security issues. I also tried to improve the descriptions around CORS a bit and provide an additional example request/response.
Seeing those changes I don't think this is a breaking change as the old …

Fix security-related CORS issues regarding to credentials #41

---

openapi.yaml

Make generic "use" verb a bit more concrete

Minor OpenID Connect `scopes` clarification

---

openapi.yaml

It could be intentional, but I noticed that the docs use "OpenID provider" instead of "OpenID Connect provider".
Technically and practically these are not the same. I think we should use "OpenID Connect" in full wherever possible

Make sure to use "OpenID Connect" in full instead of "OpenID"

---

CHANGELOG.md
openapi.yaml

Clarified that billing plans, service names and file formats must be accepted case-insensitive. #371

Clarified case-insensitivity

---

CHANGELOG.md
openapi.yaml

First rough attempt to let backend pre-define a default OIDC client id, that openEO clients can use to streamline the OIDC authentication flow
discussion points and possible improvements:
- define a single `default_client_id` or allow multiple? I don't think there is a use case for multiple.
- other relevant information of OIDC client that could be relevant to openEO client? Most obvious example is  redirect URL whitelist for Authorization Code Grant.
- more instructions/constraints for backend provider about how to set up client?
to do:
- add changelog entry

Add `default_client_id` to OpenID Connect provider data

---

CHANGELOG.md
openapi.yaml

- Support a default client for OIDC
- Added a new example, also showing the default_clients

Support a default provider for OIDC + new example

---

CHANGELOG.md
errors.json
openapi.yaml

Improvements regarding signed URLs

---

CHANGELOG.md
openapi.yaml

Clarified that `POST /result` may return multiple files as a tar. #349
This is potentially already allowed, at least there's no direct exclusion of the multipart media types, but none of the clients seem to really handle it.

Multiple files returned by sync. processing #349

---

CHANGELOG.md
openapi.yaml

Clarified allowed characters in the `path` for uploaded user files, related to a PR I'll issue soon in processes.
Although this is a "new restriction" in the API, I'd argue this is non-breaking as no OS I'm aware of allows those characters anyway and thus files paths containing such characters would be rejected anyway.

Clarified allowed characters in the `path` for uploaded user files

---

CHANGELOG.md
openapi.yaml

Fixes/Implements #410.
Could someone verify that my understanding of the authorization_code flow is correct and doesn't require a client_secret?

OIDC: Allow auth code flow and device flow for default clients

---

CHANGELOG.md
openapi.yaml

See issue #416 and discussions around private collections in openEO Platform.
This is not really a new thing, but more a clarification for clients that this behavior can be useful.

Clarify: Send token to discovery endpoints #416

---

CHANGELOG.md
openapi.yaml

Adds a STAC metadata field to implement #396

Explicitly specify metadata filters for collections #396

---

CHANGELOG.md
openapi.yaml

Implements suggestion from issue #430 as a parameter.

Support partial/incomplete batch job results #430

---

CHANGELOG.md
errors.json
openapi.yaml

Fixes the situation around the issues raised in #425 and #426.

Clarify (default) billing plans

---

CHANGELOG.md
extensions/federation/README.md

A first draft for the federation extension, all up to discussion, it's really just capturing ideas right now.
Rendered version: https://github.com/Open-EO/openeo-api/blob/federation-extension/extensions/federation/README.md
Related issue: https://github.com/openEOPlatform/architecture-docs/issues/188

Federation Extension

---

openapi.yaml

http://www.gdal.org/formats_list.html  and https://gdal.org/ogr_formats.html  give 404

Update broken links to file format GDAL codes

---

CHANGELOG.md
errors.json
openapi.yaml

Several improvements around estimates, costs and budgets:
- Don't require that the estimated costs are the upper limit. Services may specify the costs more freely depending on their terms of service.
- If a batch job can't be estimated reliably, a `EstimateComplexity` error should be returned. Fixes #443
- `GET /me`: Clarify the behavior of the field `budget`, which was incorrectly inherited from the resource budget field and thus the description did not make a lot of sense.
- Minimum value for resource `costs` and `budget` is 0.

Several improvements for estimates, budget and costs #443

---

.spectral.yml
CHANGELOG.md
openapi.yaml
package.json

Related issues:
- https://github.com/stoplightio/spectral/issues/1972
- https://github.com/stoplightio/spectral/issues/1971
- https://github.com/stoplightio/spectral/issues/1271
And fix some issues in the OpenAPI file that have been reported by Spectral v6.

Upgrade to Spectral v6

---

CHANGELOG.md
openapi.yaml

Fixes #462
- Explicitly mention the use of HTTP content negotiation
- Clarify that the default charset is UTF-8 [#462](https://github.com/Open-EO/openeo-api/issues/462)

Clarify that UTF-8 is the default charset #462

---

CHANGELOG.md
extensions/commercial-data/README.md
extensions/federation/README.md
openapi.yaml

Partially implements #186
The `/conformance` endpoints is now generally used for OGC APIs, STAC API and openEO. All openEO and all extensions got individual conformance classes. #186
This will become useful when we submit the openEO API to OGC as community standard.

Conformance classes / OGC API and STAC API alignment

---

CHANGELOG.md
openapi.yaml

Clarify that `enabled` is required by removing the default value. #473

---

CHANGELOG.md
openapi.yaml

Minor additions to the API only, Mostly reflecting the changes in https://github.com/stac-extensions/datacube/pull/10 and the addition to the JSON Schema for the new `datacube` subtype.

Vector data cubes

---

CHANGELOG.md
openapi.yaml

Add minimum log_level parameter for GET /../logs #485

---

CHANGELOG.md
README.md
extensions/processing-parameters/.spectral.yml
extensions/processing-parameters/README.md
extensions/processing-parameters/openapi.yaml
extensions/processing-parameters/package.json
extensions/remote-process-definition/README.md
openapi.yaml

Adds the Processing Parameters Extension.
This extension adds a new endpoint (`GET /processing_options`)
to discover the additional processing options that a back-end offers.
Additionally, this extension allows to provide specific default values for user-defined processes (UDPs, see below).
Implements #276 and #545

Processing Parameters Extension #276 #545
